// <autogenerated />
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("DotSpatial.Projections")]
[assembly: AssemblyDescription("For working with Projections and coordinate systems. A port of the popular proj4 C++ library to C#.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyProduct("DotSpatial.Projections")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
// Assembly marked as compliant.
[assembly: CLSCompliant(true)]
// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

[assembly: InternalsVisibleTo("DotSpatial.Projections.Tests")]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("f29830b5-1134-4a44-bef2-22d3143b618a")]